In [6]:
import urllib.request

# 저자 깃허브 저장소의 실제 애플 데이터 csv 주소
url = "https://raw.githubusercontent.com/yhilpisch/py4at/master/data/AAPL.csv"
save_path = "AAPL.csv"

# 다운로드 실행
urllib.request.urlretrieve(url, save_path)
print("AAPL.csv 다운로드 완료!")

AAPL.csv 다운로드 완료!

In [7]:
fn = 'AAPL.csv'

In [8]:
with open(fn, 'r') as f:
    for _ in range(5):
        print(f.readline(), end='')

Date,HIGH,CLOSE,LOW,OPEN,COUNT,VOLUME
2020-04-01,248.72,240.91,239.13,246.5,460606.0,44054638.0
2020-04-02,245.15,244.93,236.9,240.34,380294.0,41483493.0
2020-04-03,245.7,241.41,238.9741,242.8,293699.0,32470017.0
2020-04-06,263.11,262.47,249.38,250.9,486681.0,50455071.0

In [9]:
import csv

In [10]:
csv_reader=csv.reader(open(fn,'r'))
data = list(csv_reader)

data[:5]

[['Date', 'HIGH', 'CLOSE', 'LOW', 'OPEN', 'COUNT', 'VOLUME'],
 ['2020-04-01',
  '248.72',
  '240.91',
  '239.13',
  '246.5',
  '460606.0',
  '44054638.0'],
 ['2020-04-02',
  '245.15',
  '244.93',
  '236.9',
  '240.34',
  '380294.0',
  '41483493.0'],
 ['2020-04-03',
  '245.7',
  '241.41',
  '238.9741',
  '242.8',
  '293699.0',
  '32470017.0'],
 ['2020-04-06',
  '263.11',
  '262.47',
  '249.38',
  '250.9',
  '486681.0',
  '50455071.0']]

In [11]:
csv_reader

In [12]:
csv_reader = csv.DictReader(open(fn,'r'))
data = list(csv_reader)

data[:3]

[{'Date': '2020-04-01',
  'HIGH': '248.72',
  'CLOSE': '240.91',
  'LOW': '239.13',
  'OPEN': '246.5',
  'COUNT': '460606.0',
  'VOLUME': '44054638.0'},
 {'Date': '2020-04-02',
  'HIGH': '245.15',
  'CLOSE': '244.93',
  'LOW': '236.9',
  'OPEN': '240.34',
  'COUNT': '380294.0',
  'VOLUME': '41483493.0'},
 {'Date': '2020-04-03',
  'HIGH': '245.7',
  'CLOSE': '241.41',
  'LOW': '238.9741',
  'OPEN': '242.8',
  'COUNT': '293699.0',
  'VOLUME': '32470017.0'}]

In [14]:
sum([float(l['CLOSE']) for l in data]) / len(data)

272.3861904761905

In [16]:
import pandas as pd

data = pd.read_csv(fn, index_col=0, parse_dates=True) #fn파일을 읽어오고, 첫 열을 인덱스로 지정, 그 열이 날짜니까 날짜 형식으로 인식

data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 21 entries, 2020-04-01 to 2020-04-30
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HIGH    21 non-null     float64
 1   CLOSE   21 non-null     float64
 2   LOW     21 non-null     float64
 3   OPEN    21 non-null     float64
 4   COUNT   21 non-null     float64
 5   VOLUME  21 non-null     float64
dtypes: float64(6)
memory usage: 1.1 KB

In [17]:
data.tail()

              HIGH   CLOSE     LOW    OPEN     COUNT      VOLUME
Date
2020-04-24  283.01  282.97  277.00  277.20  306176.0  31627183.0
2020-04-27  284.54  283.17  279.95  281.80  300771.0  29271893.0
2020-04-28  285.83  278.58  278.20  285.08  285384.0  28001187.0
2020-04-29  289.67  287.73  283.89  284.73  324890.0  34320204.0
2020-04-30  294.53  293.80  288.35  289.96  471129.0  45765968.0

In [18]:
data['CLOSE'].mean()

np.float64(272.38619047619056)

In [24]:
data.to_excel('data/appl.xlsx',sheet_name='AAPL')

In [25]:
data.to_json('data/appl.json')

In [26]:
ls -n data/

total 12
-rw-r--r-- 1 0 0 3067 Jun 22 09:18 appl.json
-rw-r--r-- 1 0 0 6010 Jun 22 09:17 appl.xlsx

In [32]:
data_copy_1 = pd.read_excel('data/aapl.xlsx', sheet_name='AAPL', index_col=0)

In [33]:
data_copy_1.head()

              HIGH   CLOSE       LOW    OPEN   COUNT    VOLUME
Date
2020-04-01  248.72  240.91  239.1300  246.50  460606  44054638
2020-04-02  245.15  244.93  236.9000  240.34  380294  41483493
2020-04-03  245.70  241.41  238.9741  242.80  293699  32470017
2020-04-06  263.11  262.47  249.3800  250.90  486681  50455071
2020-04-07  271.70  259.43  259.0000  270.80  467375  50721831

In [34]:
data_copy_2 = pd.read_json('data/aapl.json')

In [35]:
data_copy_2.head()

              HIGH   CLOSE       LOW    OPEN   COUNT    VOLUME
2020-04-01  248.72  240.91  239.1300  246.50  460606  44054638
2020-04-02  245.15  244.93  236.9000  240.34  380294  41483493
2020-04-03  245.70  241.41  238.9741  242.80  293699  32470017
2020-04-06  263.11  262.47  249.3800  250.90  486681  50455071
2020-04-07  271.70  259.43  259.0000  270.80  467375  50721831

In [36]:
!rm data/*

In [37]:
import configparser
config = configparser.ConfigParser()
config.read('config/pyalgo.cfg')

['config/pyalgo.cfg']

In [47]:
# 2. 데이터 가져오기
import yfinance as yf

# 책의 BCHAIN/MKPRU 데이터와 맞추기 위해 2015년부터 2021년까지 가져오기
data = yf.download('BTC-USD', start='2015-01-01', end='2021-01-01')

# 3. 책의 컬럼 이름과 맞춰주기 (필요한 경우 Close만 추출)
# data = data[['Close']] 

print(data.head())

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker         BTC-USD     BTC-USD     BTC-USD     BTC-USD   BTC-USD
Date
2015-01-01  314.248993  320.434998  314.002991  320.434998   8036550
2015-01-02  315.032013  315.838989  313.565002  314.079010   7860650
2015-01-03  281.082001  315.149994  281.082001  314.846008  33054400
2015-01-04  264.195007  287.230011  257.612000  281.145996  55629100
2015-01-05  274.473999  278.341003  265.084015  265.084015  43962800

In [48]:
data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2192 entries, 2015-01-01 to 2020-12-31
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Close, BTC-USD)   2192 non-null   float64
 1   (High, BTC-USD)    2192 non-null   float64
 2   (Low, BTC-USD)     2192 non-null   float64
 3   (Open, BTC-USD)    2192 non-null   float64
 4   (Volume, BTC-USD)  2192 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 102.8 KB

In [51]:
data['Close'].resample('YE').last()

Ticker           BTC-USD
Date
2015-12-31    430.566986
2016-12-31    963.742981
2017-12-31  14156.400391
2018-12-31   3742.700439
2019-12-31   7193.599121
2020-12-31  29001.720703

In [52]:
# 퀀들의 'FSE/SAP_X' 대신 야후의 'SAP.DE' 티커 사용
data = yf.download('SAP.DE', start='2018-01-01', end='2023-10-01')

# 데이터 확인
print(data.head())

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open   Volume
Ticker         SAP.DE     SAP.DE     SAP.DE     SAP.DE   SAP.DE
Date
2018-01-02  80.565872  81.564259  79.975519  81.043360  2334984
2018-01-03  81.668442  82.171980  80.418280  80.739504  2346852
2018-01-04  82.553963  82.849143  81.902838  82.145930  2403598
2018-01-05  83.726013  83.726013  82.658165  82.658165  2114301
2018-01-08  83.578400  84.186120  83.179044  84.107982  1790705

In [53]:
data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1461 entries, 2018-01-02 to 2023-09-29
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   (Close, SAP.DE)   1461 non-null   float64
 1   (High, SAP.DE)    1461 non-null   float64
 2   (Low, SAP.DE)     1461 non-null   float64
 3   (Open, SAP.DE)    1461 non-null   float64
 4   (Volume, SAP.DE)  1461 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 68.5 KB